### ISSUE TITLE
Blocking doesn't work

### ISSUE THREAD

**Issue by kktrnr** [satsukitv/twitter-block-chain#7] opened 2018-05-09 16:52 UTC
Blocking has stopped working & is just listing errors instead of actually blocking. Have problems with harrassers in my field & need this tool to avoid.

**Comment by ceceradio** [comment] 2018-05-09 16:52
hey there! this is a duplicate of #5, please check out that issue for more information (see the bottom 2 posts)

**Closed as completed by ceceradio** 2018-05-09 16:52 UTC
