### ISSUE TITLE
Block Chain not currently allowing blocks

### ISSUE THREAD

**Issue by AnonymouslyAnonymous** [satsukitv/twitter-block-chain#9] opened 2018-05-20 01:40 UTC
Known issue or troubleshooting steps anyone?

![screen shot 2018-05-19 at 9 39 10 pm](https://user-images.githubusercontent.com/39448827/40274742-255fcef0-5bad-11e8-9d03-19fc944ea949.png)

**Comment by ceceradio** [comment] 2018-05-20 15:39
hey there! this is a duplicate of #5, please check out that issue for more information (see the bottom 2 posts)

**Closed as completed by ceceradio** 2018-05-20 15:39 UTC
