### ISSUE TITLE
All attempted blocks return errors.

### ISSUE THREAD

**Issue by cristynhoward** [satsukitv/twitter-block-chain#5] opened 2018-04-27 15:23 UTC
The Chrome extension is completely non-functional, now. Every attempted block gets reported as an error.

I noticed it a few days ago.

EDIT: someone else has noticed this issue as well, see screen cap below

<img width="573" alt="screen shot 2018-04-27 at 11 24 14 am" src="https://user-images.githubusercontent.com/11858567/39370690-8f2dce60-4a0d-11e8-9397-fb76749dd14d.png">

**Comment by ceceradio** [comment] 2018-04-27 15:25
Still works for me. Additional info? Browser? Can you provide screenshots of web inspector? network tab? error'd out request responses?

**Comment by Phrobbert** [comment] 2018-04-27 17:42
Looks like Twitter may be blocking the extension, it returns a 403 error.

![image](https://user-images.githubusercontent.com/38793696/39376728-95eac1da-4a4a-11e8-9213-6ff4a7987e98.png)

**Comment by ceceradio** [comment] 2018-04-27 17:45
it's possible you are being throttled. have/had you been using the extension extensively before the errors started happening?

the web API calls our tool uses have relatively high API call limits since it's intended to be used by the twitter app and not our extension. that being said, those API call limits are undocumented, so i have no idea when that throttling starts to occur.

you may have luck trying the extension on another computer or waiting out out the throttling if that's what's happening. if its still broke after 24 hours, checking the request response in the network tab would be my next ask to try and figure out whats going on

**Comment by kmkm0408** [comment] 2018-04-27 18:14
![20180428_031317](https://user-images.githubusercontent.com/38793545/39378083-4a2584c2-4a92-11e8-8396-93f9acae5a98.png)
Rotating the block chain will continue to produce an error that was not in the past.
You could just a few months ago, if you ran over a thousand people around a block chain, you could get a block.
Now, if I turn on the current program, I keep getting errors.
It looks like a program error. Please look at it and fix it.

**Comment by ceceradio** [comment] 2018-04-27 18:18
Folks I need a bit more info if I'm going to be able to help.
Can you please open the *Network* tab in your web inspector, type "block" into the filtering menu, and then select a block request that was got an error. Select the "Preview" or "Response" tab and copy the results into a message here.

![image](https://user-images.githubusercontent.com/509475/39378222-c74f9c2a-4a25-11e8-9679-97b648b10a35.png)

**Comment by kmkm0408** [comment] 2018-04-27 18:30
This is how the error will occur. I think it's a program error.
Apparently, a few months ago, I turned around this program to spin blocks with more than 1,000 accounts.
And then I said, " Well, it's a mistake, but I just switched it today for the first time. I always don't want to create an account.
I used this program without any errors. Therefore, please check. There is no problem with the computer at all. because
I've been using this program on my own computer.I am very sad.
I would like to use this program without any errors.
![20180428_032626](https://user-images.githubusercontent.com/38793545/39378849-7f88a5b6-4a94-11e8-9237-a9685a9ed43e.png)

**Comment by ceceradio** [comment] 2018-04-27 18:31
@kmkm0408 can you please click one of the "block" entries in the list from your screenshot. Then, copy+paste the text from the "Preview" or "Response" tabs?

**Comment by kmkm0408** [comment] 2018-04-27 18:35
If you press it as you want, I will be Korean. Is it okay?

{"message":"해당 작업을 실행하실 수 없는 계정일 수 있습니다. <a role=\"button\" class=\"js-reload\" href=\"#\">이 페이지 새로 고침</a> 을 하신 후에 다시 시도해주세요."}


A brief description would suggest that the account is not capable of running the task. Then, I would like to refresh the page and try again. But if it's a simple error, every account I want to use a chain block has this error.

**Comment by ceceradio** [comment] 2018-04-27 18:38
@kmkm0408 thank you! that's very strange. I am unsure if this is a problem with the program or with twitter. I'm trying to debug it...

**Comment by kmkm0408** [comment] 2018-04-27 18:39
You mean it could be an internal stream of Twitter?

**Comment by ceceradio** [comment] 2018-04-27 18:40
@kmkm0408 yes, its possible that twitter's servers are preventing the addition of blocks either due to throttling (artificial limit of the number of blocks) or due to server overload...

**Comment by kmkm0408** [comment] 2018-04-27 18:41
But if you search, you'll also find some people who can run programs.

**Comment by ceceradio** [comment] 2018-04-27 18:48
@kmkm0408 yes i am aware. i am included in that group. however, twitter is known to throttle certain IPs/browsers when too many requests are made. Additionally because twitter is a network of servers, some regional servers may be overloaded while others may not. it's hard for me to debug with twitter doesn't give me enough information.

**Comment by kmkm0408** [comment] 2018-04-27 18:49
If there is any error in the program, please correct it and let me know because I desperately need to write the program.

**Comment by kmkm0408** [comment] 2018-04-27 19:02
I would like to use this program for a long time. Please, it is just a program error.

**Comment by ceceradio** [comment] 2018-04-27 19:13
@kmkm0408 have you tried signing out and signing in again, then trying to use twitter block chain again?

**Comment by ceceradio** [comment] 2018-04-27 19:15
@cristynhoward @Phrobbert could you two both give me response bodies similar to how kmkm0408 did? thank you.

**Comment by kmkm0408** [comment] 2018-04-27 19:25
Yes, of course I've logged out and run the program, but it hasn't run. I think there is a kind of a reaction like this @Phrobbert

**Comment by kmkm0408** [comment] 2018-04-27 19:27
Please let me know exactly what I need to tell you. I'll give you my best answer.

**Comment by kmkm0408** [comment] 2018-04-28 02:40
@satsukitv Isn't this a program error?

**Comment by ystros** [comment] 2018-04-28 06:27
I started seeing this issue as well earlier today. Running Twitter Block Chain on a list of followers results in 403 Forbidden errors for each follower it attempts to block, each with the response:
```json
{"message":"Your account may not be allowed to perform this action. Please <a role=\"button\" class=\"js-reload\" href=\"#\">refresh the page</a> and try again."}
```

Using block directly through the twitter.com web interface continues to work properly, so if it's a rate-limiting issue, the official web interface doesn't seem to be affected.

I also attempted signing out of Twitter and back in, which did not fix the issue.

I do notice a difference in the request form data for the web interface vs TBC. I'm not sure it's significant, but I'll provide it. Sensitive info such as auth tokens and user IDs redacted, but they remain identical between the two requests. Both requests seem to be hitting the same URL (`https://twitter.com/i/user/block`).

Block request via twitter.com web interface (works correctly):
```
authenticity_token: [REDACTED]
challenges_passed: false
handles_challenges: 1
impression_id: 
user_id: [REDACTED]
```

Block request via TBC (403 error):
```
authenticity_token: [REDACTED]
block_user: true
impression_id: 
report_type: 
screen_name: [REDACTED]
user_id: [REDACTED]
```

Let me know if there's additional info that would be helpful tracking this down!

EDIT: If relevant, these results are from Google Chrome 65.0.3325.181 on Mac OS X.

**Comment by kmkm0408** [comment] 2018-04-28 06:32
Hello! Then, do you think it is an internal problem on Twitter or an error on this program? @ystros

**Comment by shinglesnowbeam** [comment] 2018-04-28 08:46
Hi.
I use this and "Twitter One Click Block" extension, and both could not be used at the same time from some day before. So I guessed that there was any change on Twitter.
"Twitter One Click Block" error is fixed yesterday. maybe they have some hint to fix.

**Comment by Phrobbert** [comment] 2018-04-28 15:54
Late returning to this thread but I get the same results as Ystros.

> message:"Your account may not be allowed to perform this action. Please <a role="button" class="js-reload" href="#">refresh the page</a> and try again."

**Comment by ceceradio** [comment] 2018-04-28 15:58
hi folks. if i get time this weekend i will try and release an update that may help. without experiencing this issue myself it's going to be difficult to provide a quick solution, though.

**Comment by kmkm0408** [comment] 2018-04-28 16:25
Haven't you experienced this error yet?

**Comment by kmkm0408** [comment] 2018-04-30 17:03
I'd like to know if I still haven't resolved my program errors.

**Comment by kmkm0408** [comment] 2018-05-01 09:28
I'd like to know if I still haven't resolved my program errors.

**Comment by cristynhoward** [comment] 2018-05-01 20:26
Late getting back to this thread, but more diagnostic info can't hurt. I'm getting exactly what the other users have reported.

Using Chrome 65.0.3325.181 on Mac OS X El Capitan 10.11.6.

<img width="464" alt="screen shot 2018-05-01 at 4 22 06 pm" src="https://user-images.githubusercontent.com/11858567/39491915-dc157be6-4d5b-11e8-9f54-27be1179557e.png">

<img width="547" alt="screen shot 2018-05-01 at 3 58 46 pm" src="https://user-images.githubusercontent.com/11858567/39491262-b3ca6f2c-4d59-11e8-9606-453ba9287cf8.png">

Each failed block results in status 403 and a "Response" message reading

> {"message":"Your account may not be allowed to perform this action. Please <a role=\"button\" class=\"js-reload\" href=\"#\">refresh the page</a> and try again."}

And I also noticed a similar request format discrepancy to the one that user ystros mentioned. 

Failed block attempts via the extension have the format:

> authenticity_token: REDACTED
> block_user: true
> impression_id: 
> report_type: 
> screen_name: REDACTED
> user_id: REDACTED

whereas successful ones made using the web interface have the format:

> authenticity_token: REDACTED
> challenges_passed: false
> handles_challenges: 1
> impression_id: 
> lang: en
> user_id: REDACTED

**Comment by jay-visitseattle** [comment] 2018-05-02 19:54
I am seeing this issue as well today (though I haven't tried running this extension in a while).

I am using a Asus Laptop running Windows 10.

*Request Headers:*
```
Request URL: https://twitter.com/i/user/block
Request Method: POST
Status Code: 403 
Remote Address: 104.244.42.129:443
Referrer Policy: no-referrer-when-downgrade
```

*Response:*
```
{"message":"Your account may not be allowed to perform this action. Please <a role=\"button\" class=\"js-reload\" href=\"#\">refresh the page</a> and try again."}
```

None of the blocking actions succeeded for the initial run, or the run I did a little later to make sure I wasn't being throttled. I hadn't used this plugin in at least a month previously.

Let me know if I can offer any more information or do anything to help debug. This is an excellent plugin!

**Comment by cicifluff** [comment] 2018-05-03 23:33
I am getting the same errors. No one I block actually gets blocked. It used to work for me.

**Comment by kmkm0408** [comment] 2018-05-04 17:33
Have you found the cause of the error yet? Or are you in a situation where you can't solve the error because it's internal to Twitter? I want to know.

**Comment by ceceradio** [comment] 2018-05-04 17:53
Currently Chrome has a bug where the content_scripts injected into a page, from an extension, are not considered to be on the same site as the page itself. So sites that utilize SameSite cookies will not be able to send requests with those cookies attached. 
https://groups.google.com/a/chromium.org/forum/#!msg/extensions-reviews/SoLuNWUCvnA/d8aAhyxzAAAJ

Fortunately, Firefox doesn't have this problem. I have updated the Firefox plugin to the latest version (thanks @gaeulbyul for putting in the work on that code). 

https://addons.mozilla.org/en-US/firefox/addon/twitter-block-chain/

For now I am going to leave this issue open while I weigh options for trying to get the Chrome version working again.

**Comment by ceceradio** [comment] 2018-05-05 02:39
Update: Chrome Beta (67) has the code to fix the issue. When Chrome 67 hits stable the extension will be usable again on normal Chrome installations. Closing the issue since there two workarounds and a fix will eventually be delivered through standard Chrome updates.

**Closed as completed by ceceradio** 2018-05-05 02:39 UTC

**Comment by ceceradio** [comment] 2018-05-23 18:07
6 more days :^)
![image](https://user-images.githubusercontent.com/509475/40442780-90ed32d8-5e92-11e8-8949-454d8537c247.png)

**Comment by ceceradio** [comment] 2018-05-29 21:37
chrome 67 is rolling out! please check for updates in chrome and report back if there are any issues on chrome 67! Thank you!
