### ISSUE TITLE
Blocking doesn't work any more

### ISSUE THREAD

**Issue by AntonKukoba1** [satsukitv/twitter-block-chain#6] opened 2018-05-08 19:33 UTC
![image](https://user-images.githubusercontent.com/35240638/39778733-cff1278e-530f-11e8-8465-b5317245b5fa.png)
all blocking attempts are failing

**Comment by ceceradio** [comment] 2018-05-08 19:34
Duplicate of #5

**Closed as completed by ceceradio** 2018-05-08 19:34 UTC

**Comment by AntonKukoba1** [comment] 2018-05-08 19:37
ok
